### ISSUE TITLE
Berserker Stance not giving 3% crit bonus vs. higher level mobs

### ISSUE THREAD

**Issue by magey** [magey/classic-warrior#17]
Thanks to extensive testing done on the beta by Puffymuffins, Towneh, and Vilius, we've encountered what appears to be a pretty significant bug with Berserker Stance. Against +3 level mobs, Berserker Stance's 3% crit bonus is not applying to our attacks and as a result our effective crit chance is 3% lower than it should be. We're aware of the 1% crit reduction per level difference, this is an additional 3% reduction. If we attack mobs of the same level in Berserker Stance, then we are seeing expected crit values. Attacking +3 level mobs while in Defensive or Battle Stance is also giving us expected crit values as you can see [here](https://github.com/magey/classic-warrior/wiki/Attack-table#test-breakdown). Some measurements follows:

**Note:** all hits are white only

***

### Target at +3 levels, +5 weapon skill (n=5178)
Player | Skill | Crit | Target | Attacks | Log
:---:|:---:|:---:|:---:|:---:|:---:
Puffymuffins (40)|205/205|18.67%|Longtooth Howler (43)|1753|[link](https://github.com/magey/classic-warrior/files/3273915/Puffymuffins_Bloodthirst_2019-06-08_205_skill_18.67_crit_40v43.txt)
Towneh (40)|205/205|14.04%|Steeljaw Snapper (43)|3425|[link](https://github.com/magey/classic-warrior/files/3273938/Towneh_Berserker_Stance_BT_205_skill_14.04_crit_40v43.txt)

**Puffymuffins vs. Longtooth Howler**
* Hit: **14.55% ±1.68%** (255)
* Crit: **12.44% ±1.58%** (218)
* Miss: **6.05% ±1.14%** (106)
* Parry: **13.98% ±1.66%** (245)
* Dodge: **6.79% ±1.20%** (119)
* Block: **4.79% ±1.02%** (84)
* Glancing: **41.41% ±2.35%** (726)
* Glance Reduction: **~15.03%**

**Towneh vs. Steeljaw Snapper**
* Hit: **20.73% ±1.39%** (710)
* Crit: **8.38% ±0.95%** (287)
* Miss: **5.69% ±0.79%** (195)
* Parry: **13.26% ±1.16%** (454)
* Dodge: **6.13% ±0.82%** (210)
* Block: **5.02% ±0.75%** (172)
* Glancing: **40.79% ±1.68%** (1397)
* Glance Reduction: **~14.96%**

**Overall crit chance (weighted average)**
* Spell book: **15.61%**
* Expected: **12.61%** (-3% crit suppression)
* Measured: **9.75% ±0.82%** (505)

***

### Equal level target (n=3803)
Player | Skill | Crit | Target | Attacks | Log
:---:|:---:|:---:|:---:|:---:|:---:
Puffymuffins (40)|200/200|18.47%|Longtooth Runner (40)|2043|[link](https://github.com/magey/classic-warrior/files/3273880/Puffymuffins_Beserker_Stance_2019-06-08_200_skill_18.47_crit_40v40.txt)
Vilius (35)|200/200|15.71%|Elder Stranglethorn Tiger (35)|1760|[link](https://github.com/magey/classic-warrior/files/3273883/Vilius_Berserker_Stance_DW_200_skill_35v35.txt)

**Puffymuffins vs. Longtooth Runner**
* Hit: **51.44% ±2.21%** (1051)
* Crit: **17.57% ±1.68%** (359)
* Miss: **4.60% ±0.93%** (94)
* Parry: **4.70% ±0.94%** (96)
* Dodge: **5.29% ±0.99%** (108)
* Block: **5.68% ±1.02%** (116)
* Glancing: **10.72% ±1.37%** (219)
* Glance Reduction: **~5.14%**

**Vilius (dual wield) vs. Elder Stranglethorn Tiger**
* Hit: **36.31% ±2.29%** (639)
* Crit: **16.19% ±1.76%** (285)
* Miss: **23.69% ±2.03%** (417)
* Parry: **4.55% ±0.99%** (80)
* Dodge: **5.00% ±1.04%** (88)
* Block: **5.23% ±1.06%** (92)
* Glancing: **9.03% ±1.37%** (159)
* Glance Reduction: **~4.99%**

**Overall crit chance (weighted average)**
* Spell book: **17.19%**
* Expected: **17.19%**
* Measured: **16.93% ±1.22%** (644)

**Comment by Dalleren** [comment]
The results showing a 12.44% ±1.58% chance for a critical hit against the Longtooth Howler seems to be reasonable. However against the Steeljaw Snapper the results are far off. Perhaps this is simply a matte
r of statistical significance. I would assume that you are using a 95% confidence intervals to estimate the uncertainties.

**Comment by magey** [comment]
Yes these are 95% confidence intervals. You can see in our many other tests [here](https://github.com/magey/classic-warrior/wiki/Attack-table#test-breakdown) that crit values converge rather fast to the expected results. This is also the case in the same-level test with Berserker Stance on this issue. In the case of the Longtooth Howler we measured ~3% less crit than expected: 18.67% spell book, 15.67% expected, 12.44% measured (~3% less). The same thing happens in the Steeljaw Snapper test: spell book 14.04%, expected 11.04%, measured 8.38% (~3% less). So as you can see these trends repeats and at 5k+ hits the confidence intervals are pretty low.

**Comment by Torakwarrior** [comment]
[Torak WoWCombatLog no cruelty zerker.txt](https://github.com/magey/classic-warrior/files/3379776/Torak.WoWCombatLog.no.cruelty.zerker.txt)

These attacks were made with level 40 troll warrior in berserker stance with no talents vs level 43 Steeljaw Snapper. Spellbook notes 11.41% crit chance. No agi buffs or +crit% gear was used, 111 agi on character sheet.

**Comment by Torakwarrior** [comment]
[Torak WoWCombatLog 5 cruelty battle.txt](https://github.com/magey/classic-warrior/files/3379866/Torak.WoWCombatLog.5.cruelty.battle.txt)
These attacks were made with level 40 troll warrior in battle stance with 5/5 cruelty vs level 43 steeljaw snapper. Spellbook notes 13.41% crit chance, same gear and buffs as last data set.

**Comment by Torakwarrior** [comment]
[Torak WoWCombatLog 5 cruelty zerker.txt](https://github.com/magey/classic-warrior/files/3379947/Torak.WoWCombatLog.5.cruelty.zerker.txt)
These attacks were made with level 40 troll warrior in berserker stance with 5/5 cruelty vs level 43 steeljaw snapper. Spellbook notes 16.41% crit chance, same gear and buffs as last two data sets.

**Comment by 3Pyte** [comment]
[WoWCombatLog - 17.43% crit test.txt](https://github.com/magey/classic-warrior/files/3380630/WoWCombatLog.-.17.43.crit.test.txt)

Warrior log with 3k white hits. 5.43% base crit, 17.43% book crit. Crit aura is from 5/5 axe spec, 4/5 cruelty, and berserker stance. 205 weapon skill. Results: 12.6% crit.

Exact same gear as my shield slam tests elsewhere. Only talents differ.

**Comment by Torakwarrior** [comment]
[Torak WoWCombatLog cruelty axe zerker.txt](https://github.com/magey/classic-warrior/files/3380843/Torak.WoWCombatLog.cruelty.axe.zerker.txt)

These attacks were made with level 40 troll warrior in berserker stance with 5/5 cruelty and 5/5 axe spec vs level 43 steeljaw snapper. Spellbook notes 21.19% crit chance, 108 agi on character sheet. Sword of omen used in previous tests swapped out for cleaver (white vendor item) for axe spec.

**Comment by magey** [comment]
Blizzard responded [here](https://us.forums.blizzard.com/en/wow/t/bug-berserker-stance/196414) and confirmed this is not a bug; there is suppression to +crit gained from auras (talents/gear/buffs/consumables/etc.) that is independent from the suppression due to weapon skill/defense.

We've done some very extensive research [over here](https://github.com/magey/classic-warrior/wiki/Crit-aura-suppression) which confirmed Blizzard's response and determined the crit aura suppression is likely a flat ~1.8% reduction.
