### ISSUE TITLE
Instant attack normalization uses wrong multipliers

### ISSUE THREAD

**Issue by magey** [magey/classic-warrior#20]
Extensive testing on the AV beta realm (build 30786) has revealed a critical bug with instant attack normalization. It seems that all weapon types (including ranged weapons) are using [Legion normalization multipliers](https://www.reddit.com/r/wow/comments/6xohkh/since_73_standard_attackspeed_across_every_weapon/) instead of vanilla [melee](https://web.archive.org/web/20061013154236/http://www.worldofwarcraft.com:80/patchnotes/patch1p8.html) and [ranged](https://web.archive.org/web/20061013154151/http://www.worldofwarcraft.com/patchnotes/patch1p10.html) ones. Here they are for reference:

Weapon type|Vanilla multiplier|Legion multiplier
:---:|:---:|:---:
Two-handed|3.3|3.6
One-handed|2.4|2.6
Dagger|1.7|1.8
Ranged|2.8|3.0

### Test results

Note: all calculations done on unmitigated damage numbers from the combat log, all characters used are level 58 templates

Player | Class | Attack power | Weapon type | Speed | Damage | Log
:---:|:---:|:---:|:---:|:---:|:---:|:---:
insec|Warrior|692|[2H Axe](https://classic.wowhead.com/item=926/battle-axe)|3.80|46-70|[link](https://github.com/magey/classic-warrior/files/3293736/insec_Normalization_MS_Rank_3_692_AP_46_70_2H_Axe.txt)
insec|Warrior|692|[2H Sword](https://classic.wowhead.com/item=13053/doombringer)|2.80|115-173|[link](https://github.com/magey/classic-warrior/files/3293750/insec_Normalization_MS_Rank_3_692_AP_115_173_2H_Sword.txt)
Towneh|Warrior|692|[2H Axe](https://classic.wowhead.com/item=926/battle-axe)|3.80|46-70|[link](https://github.com/magey/classic-warrior/files/3293758/Towneh_Normalization_692_AP_46-70_2H_Axe.txt)
dmzor|Rogue|565|[1H Sword](https://classic.wowhead.com/item=851/cutlass)|2.20|10-20|[link](https://github.com/magey/classic-warrior/files/3293761/dmzor_Normalization_SS_Rank_8_565_AP_10-20_1H_Sword.txt)
dmzor|Rogue|567|[Dagger](https://classic.wowhead.com/item=2139/dirk)|1.60|1-3|[link](https://github.com/magey/classic-warrior/files/3293765/dmzor_Normalization_SS_Rank_8_567_AP_1-3_Dagger.txt)
dmzor|Hunter|622|[Crossbow](https://itemization.info/item/15808)|2.70|20-20|[link](https://github.com/magey/classic-warrior/files/3293770/dmzor_Normalization_Aimed_Shot_Rank_1_622_RAP_20-20_Crossbow.txt)

**insec (2H Axe)**
* Damage range (3.3): **692/14*3.3+[46..70] = ~209-233**
* Damage range (3.6): **692/14*3.6+[46..70] = ~223-248**
* Mortal Strike (Rank 3, 135 bonus damage, 119 hits)
  * Expected range (3.3): **~344-368**
  * Expected range (3.6): **~358-383**
  * Measured range: **358-382**
* Whirlwind (Weapon damage, 145 hits)
  * Expected range (3.3): **~209-233**
  * Expected range (3.6): **~223-248**
  * Measured range: **224-247**

**insec (2H Sword)**
* Damage range (3.3): **692/14*3.3+[115..173] = ~278-336**
* Damage range (3.6): **692/14*3.6+[115..173] = ~292-351**
* Mortal Strike (Rank 3, 135 bonus damage, 111 hits)
  * Expected range (3.3): **~413-471**
  * Expected range (3.6): **~427-486**
  * Measured range: **428-484**
* Whirlwind (Weapon damage, 157 hits)
  * Expected range (3.3): **~278-336**
  * Expected range (3.6): **~292-351**
  * Measured range: **293-350**

**Towneh (2H Axe)**
* Damage range (3.3): **692/14*3.3+[46..70] = ~209-233**
* Damage range (3.6): **692/14*3.6+[46..70] = ~223-248**
* Mortal Strike (Rank 3, 135 bonus damage, 85 hits)
  * Expected range (3.3): **~344-368**
  * Expected range (3.6): **~358-383**
  * Measured range: **359-382**
* Whirlwind (Weapon damage, 71 hits)
  * Expected range (3.3): **~209-233**
  * Expected range (3.6): **~223-248**
  * Measured range: **224-247**

**dmzor (1H Sword)**
* Damage range (2.4): **565/14*2.4+[10..20] = ~106-117**
* Damage range (2.6): **565/14*2.6+[10..20] = ~114-125**
* Sinister Strike (Rank 8, 68 bonus damage, 204 hits)
  * Expected range (2.4): **~174-185**
  * Expected range (2.6): **~182-193**
  * Measured range: **182-192**

**dmzor (Dagger)**
* Damage range (1.7): **567/14*1.7+[1..3] = ~69-72**
* Damage range (1.8): **567/14*1.8+[1..3] = ~73-76**
* Sinister Strike (Rank 8, 68 bonus damage, 25 hits)
  * Expected range (1.7): **~137-140**
  * Expected range (1.8): **~141-144**
  * Measured range: **141-143**

**dmzor (Crossbow, 16.5 DPS arrows)**
* Damage range (2.8): **16.5\*2.7+622/14\*2.8+20 = ~188-189**
* Damage range (3.0): **16.5\*2.7+622/14\*3.0+20 = ~197-198**
* Aimed Shot (Rank 1, 70 bonus damage, 5 hits)
  * Expected range (2.8): **~258-259**
  * Expected range (3.0): **~267-268**
  * Measured range: **266-267**

**Comment by Scyllaqt** [comment]
Normalization is now fixed
